### ISSUE TITLE
Build tensorflow-text did not complete sucessfully

### ISSUE THREAD

**Issue by Fred-Wu** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#16] opened 2023-07-29 13:00 UTC
I created a new environment to install tensorflow and tensorflow-text step by step on Macbook M1 for Python==3.11. 

However, building tensorflow-text encounted the errors

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
Target //oss_scripts/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.042s, Critical Path: 1.43s
INFO: 55 processes: 20 internal, 35 local.
FAILED: Build did NOT complete successfully
```

Any help would be welcomed.

**Comment by Fred-Wu** [comment] 2023-07-29 14:23
Also in terms of bazel version, tensorflow already changeed it to 6.1.0, but 5.3.0 seems still be used to build text. 

[https://github.com/tensorflow/tensorflow/blob/master/.bazelversion](url)

**Comment by sun1638650145** [comment] 2023-07-30 02:13
1. Let me correct an apparent mistake: currently, the `master` branch of `tensorflow` is using `bazel 6.1.0`, while `tensorflow 2.13` still uses `bazel 5.3.0`. Consequently, `tensorflow-text 2.13` also employs `bazel 5.3.0`. If you are unsure about this, I recommend using pre-compiled wheel files.
2. Please provide detailed environmental information and the error log from your compilation process, as the given information is insufficient to determine the cause of the error.

**Comment by sun1638650145** [comment] 2023-08-07 01:42
@Fred-Wu Due to your prolonged absence in responding to this issue, I am now going to close this issue. If you have any questions, you can still reopen it.

**Closed as completed** 2023-08-07 01:42 UTC
